### ISSUE TITLE
KeyError: '_template'

### ISSUE THREAD

**Issue by Sieboldianus** [senseyeio/cupper#2]
First, thanks for sharing this repo with the world! I am having difficulties setting cupper up with my cookiecutter cloned project. 

These are my steps:
1. Install cookiecutter `pip install cookiecutter`
2. Clone template, e.g. `cookiecutter https://github.com/some/template/...`
3. Make local changes to the cookiecutter initialized repository
4. Realize that there are upstream update in `https://github.com/some/template/...`
5. Look for options to automatically include these changes, find Cupper
6. Install Cupper `pip install cupper`
7. Add original repository with cookiecutter.json and context as submodule to `/docs/`, e.g. `git submodule add https://github.com/some/template/...`
8. Run Cupper with `cupper ./docs/template/cookiecutter.json template`

Yields:
```python
Traceback (most recent call last):
  File "/home/.../miniconda3/bin/cupper", line 11, in <module>
    sys.exit(main())
  File "/home/.../miniconda3/lib/python3.7/site-packages/cupper.py", line 74, in main
    update_template(context, os.getcwd(), branch=branch)
  File "/home/.../miniconda3/lib/python3.7/site-packages/cupper.py", line 38, in update_template
    template_url = context['_template']
KeyError: '_template'
```

Where did I go wrong in my steps?

**Comment by Sieboldianus** [comment]
Got it!

The `cookiecutter.json` needs a section with `_template` (e.g. remote repository url).

Solved by adding:
```json
{
    "project_name": "Base Project",
    "_template": "https://github.com/some/template/...",
    ....
}
```
